### ISSUE TITLE
Transvision.co.id broken encryption ?

### ISSUE THREAD

**Issue by billyriantono** [SilentButeo2/webgrabplus-siteinipack#474] opened 2020-05-03 15:01 UTC
Hi team,
i try to use transvision.co.id sitepack.ini but seems it's broken , because i got error : error downloading page: Error: SecureChannelFailure (The authentication or decryption has failed.)

using latest wgplus version and donator license.

Thank you

**Comment by WGMaker** [comment] 2020-05-03 15:26
The error might be caused by a security protocol error which is fixed in V3.0.1 beta.  Try again with V3.0.2 beta ..

I don’t think it is a decryption error, the error message for that is normally different. But , pls note that any change you make to the SiteIni will corrupt the decryption. Only use it as you download it from our site..

Jan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by billyriantono** [comment] 2020-05-04 02:30
Hi Jan, 
Thank you for the response, i already update and try using 3.0.1 beta, its show : 
![image](https://user-images.githubusercontent.com/3274396/80932482-ba41eb00-8de9-11ea-89ca-40ba8e756561.png)

in 3.0.2 beta i can't use because my license is read as unregistered user :
![image](https://user-images.githubusercontent.com/3274396/80932489-cfb71500-8de9-11ea-8b6f-1075e1098508.png)

**Closed** 2020-05-13 07:58 UTC
